# Allwinner H616 H20 Pro 5G (LPDDR3/eMMC/WiFi RMII)
BOARD_NAME="H20 Pro 5G"
BOARDFAMILY="sun50iw9"
BOARD_MAINTAINER="unknown"
BOOTCONFIG="h20_pro_5g_defconfig"
SERIALCON="ttyS0"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
FORCE_BOOTSCRIPT_UPDATE="yes"
BOOTFS_TYPE="fat"
BOOT_FS_LABEL="BOOT"
OVERLAY_PREFIX="sun50i-h616"
BOOT_FDT_FILE="sun50i-h616-h20-pro-5g.dtb"
